name: MayAo-Remote-Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 1. Cài đặt môi trường Desktop XFCE và các công cụ cần thiết
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive \
            apt-get install -y \
            xfce4 xfce4-goodies \
            xorg dbus-x11 x11-xserver-utils \
            wget curl \
            --no-install-recommends
          echo "Hoàn tất cài đặt môi trường Desktop."

      - name: 2. Cài đặt XRDP và fix lỗi âm thanh (Pulse Audio)
        run: |
          # BƯỚC MỚI: Bật kho mã nguồn (deb-src) và cập nhật
          sudo sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
          sudo apt-get update
          
          # Cài đặt XRDP
          sudo apt-get install -y xrdp
          
          # Cài các gói cần thiết để build
          sudo apt-get install -y git libpulse-dev autoconf m4 intltool build-essential dpkg-dev libtool libsndfile-dev libspeexdsp-dev
          
          # Di chuyển vào thư mục /tmp để làm việc
          cd /tmp
          
          # Tải mã nguồn của PulseAudio để build module
          sudo apt-get source pulseaudio
          
          # Clone repo chứa module âm thanh
          git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git
          cd pulseaudio-module-xrdp
          
          # Trỏ biến môi trường PULSE_DIR vào thư mục mã nguồn
          export PULSE_DIR=$(ls -d /tmp/pulseaudio-*/)
          
          # Tiến hành build và cài đặt
          ./bootstrap
          ./configure
          make
          sudo make install
          echo "Đã cài đặt XRDP và fix lỗi âm thanh."

      - name: 3. Cài đặt Brave Browser và Discord
        run: |
          # Cài đặt Brave Browser
          sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
          sudo apt-get update
          sudo apt-get install -y brave-browser
          
          # Cài đặt Discord
          wget -O /tmp/discord.deb "https://discord.com/api/download?platform=linux&format=deb"
          sudo dpkg -i /tmp/discord.deb
          sudo apt-get install -f -y # Cài các dependency còn thiếu của Discord
          echo "Đã cài đặt Brave và Discord."

      - name: 4. Tạo người dùng 'yuu' với quyền root và mật khẩu
        run: |
          sudo useradd -m -s /bin/bash yuu
          echo "yuu:lt4c@2025" | sudo chpasswd
          sudo adduser yuu sudo
          echo "Đã tạo user 'yuu' và cấp quyền root."

      - name: 5. Cấu hình XRDP và tạo icon trên Desktop
        run: |
          # Cho phép XRDP sử dụng XFCE
          sudo sed -i.bak '/fi/a #xrdp multiple users configuration \nxfce4-session \n' /etc/xrdp/startwm.sh
          
          # Tạo thư mục Desktop cho user yuu
          sudo mkdir -p /home/yuu/Desktop
          
          # Copy icon Brave và Discord ra Desktop
          sudo cp /usr/share/applications/brave-browser.desktop /home/yuu/Desktop/
          sudo cp /usr/share/applications/discord.desktop /home/yuu/Desktop/
          
          # Cấp quyền sở hữu cho user yuu
          sudo chown -R yuu:yuu /home/yuu/Desktop
          sudo chmod +x /home/yuu/Desktop/*.desktop
          echo "Đã cấu hình XRDP và tạo icon ngoài Desktop."

      - name: 6. Cài đặt và chạy Tailscale để kết nối
        run: |
          # Cài đặt Tailscale
          curl -fsSL https://tailscale.com/install.sh | sh
          
          # Khởi chạy Tailscale và giữ cho máy ảo hoạt động
          echo "ĐANG CHẠY TAILSCALE..."
          echo ">>> VUI LÒNG MỞ LOGS, TÌM VÀ TRUY CẬP ĐƯỜNG LINK BÊN DƯỚI ĐỂ XÁC THỰC <<<"
          sudo tailscale up --hostname=github-vm

      - name: 7. Giữ máy ảo hoạt động
        run: |
          # Lệnh này sẽ chạy sau khi Tailscale được xác thực và giữ cho workflow không bị tắt
          echo "Đã kết nối Tailscale thành công. Máy ảo đang chạy..."
          sleep 99999
